# Generated by Django 5.0.1 on 2024-01-17 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_rename_catagory_category_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='catagory',
            new_name='category',
        ),
        migrations.RemoveField(
            model_name='products',
            name='treading',
        ),
        migrations.AddField(
            model_name='products',
            name='like',
            field=models.BooleanField(default=False, help_text='0-show,1-like'),
        ),
        migrations.DeleteModel(
            name='Cart',
        ),
    ]
